apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx1
    project: practice
    author: farrukh
  name: nginx1
  namespace: f-sadatov
spec:
  containers:
  - image: nginx:latest
    name: nginx1
    ports:
    - containerPort: 80
    resources: {}
